// <auto-generated />
using ConcertBackend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcertBackend.Migrations
{
    [DbContext(typeof(ConcertsDbContext))]
    partial class ConcertsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcertBackend.Models.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcertDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("TicketsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Concerts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ConcertBackend.Models.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId")
                        .IsUnique();

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("ConcertBackend.Models.Promocode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Promocodes");
                });

            modelBuilder.Entity("ConcertBackend.Models.Classic", b =>
                {
                    b.HasBaseType("ConcertBackend.Models.Concert");

                    b.Property<string>("Composer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Classics");
                });

            modelBuilder.Entity("ConcertBackend.Models.OpenAir", b =>
                {
                    b.HasBaseType("ConcertBackend.Models.Concert");

                    b.Property<string>("Headliner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journey")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("OpenAirs");
                });

            modelBuilder.Entity("ConcertBackend.Models.Party", b =>
                {
                    b.HasBaseType("ConcertBackend.Models.Concert");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ConcertBackend.Models.Coordinates", b =>
                {
                    b.HasOne("ConcertBackend.Models.Concert", "Concert")
                        .WithOne("Coordinates")
                        .HasForeignKey("ConcertBackend.Models.Coordinates", "ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("ConcertBackend.Models.Classic", b =>
                {
                    b.HasOne("ConcertBackend.Models.Concert", null)
                        .WithOne()
                        .HasForeignKey("ConcertBackend.Models.Classic", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcertBackend.Models.OpenAir", b =>
                {
                    b.HasOne("ConcertBackend.Models.Concert", null)
                        .WithOne()
                        .HasForeignKey("ConcertBackend.Models.OpenAir", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcertBackend.Models.Party", b =>
                {
                    b.HasOne("ConcertBackend.Models.Concert", null)
                        .WithOne()
                        .HasForeignKey("ConcertBackend.Models.Party", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcertBackend.Models.Concert", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
